<?php

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

class Model_recovery extends CI_Model {

    public function get_recovery() {

        //$selectall = "select a.NomorNasabah,a.NomorRekening,a.NamaDebitur,a.ID,a.JmlHariTunggakan as DPD, a.FacilityType,a.PlafondAmount,(SELECT b.DESCRIPTION FROM bss_ld_sub_product as b WHERE b.ID = a.FacilityType) as ket_facility, a.STARTDATEPLAFOND,a.DATEEXPIRED,DAY(a.STARTDATEPLAFOND) as cycle, TIMESTAMPDIFF(MONTH,a.STARTDATEPLAFOND,a.DATEEXPIRED) as tenor,a.KodeCabang,(select q.nama_cabang from t_m_account as q  where q.LD_Temenos = a.ID) as Cabang,a.JmlHariTunggakan as DPD_EOM,a.COL as bucked,format((SELECT d.ANNUITY_REPAY_AMT FROM bss_ld as d WHERE d.ID = a.ID) , 2) as angsuran ,format(a.BakiDebet,2) as BakiDebet,format((SELECT f.DuePokok FROM t_m_account as f WHERE f.LD_Temenos = a.ID),2) as tunggakan_pokok ,format(a.DueBunga,2) as bunga,format((SELECT g.denda from t_m_account as g WHERE g.LD_Temenos = a.ID),2) as denda,format((SELECT sum(h.denda + h.DueBunga + h.DuePokok) FROM t_m_account as h WHERE h.LD_Temenos = a.ID),2) as total_tagihan ,(SELECT i.OPEN_ACTUAL_BAL FROM bss_account as i WHERE i.ID = a.RepayPrincSettleAcc) as saldo_tabungan, (SELECT j.L_TGL_RES from bss_limit as j WHERE j.ID=a.LimitID) as tgl_restru ,(SELECT k.L_NO_RES from bss_limit as k WHERE k.ID=a.LimitID) as restru_ke, (SELECT l.ADDRESS from bss_customer as l WHERE l.ID = a.NomorNasabah) as alamat,(SELECT m.POST_CODE from bss_customer as m WHERE m.ID = a.NomorNasabah) as postcode,(SELECT n.SMS_1 from bss_customer as n WHERE n.ID = a.NomorNasabah) as notlp,(SELECT o.EMAIL_1 from bss_customer as o WHERE o.ID = a.NomorNasabah) as email from bss_cad as a where a.NomorNasabah not in (SELECT z.f_cif from t_assignment as z) GROUP BY a.NomorNasabah ORDER by MAX(a.JmlHariTunggakan)";
//        $query = "SELECT * FROM `t_accountlist_baru` LIMIT 50";
//        $query = "SELECT a.*,b.f_id,(SELECT format(SUM(d.REPAYMENT_AMOUNT),2) FROM bss_stmt_entry as d WHERE d.OUR_REFERENCE = a.ID) as repar ,b.REPAYMENT_AMOUNT from t_m_account as a LEFT JOIN bss_stmt_entry as b ON a.ID = b.OUR_REFERENCE WHERE a.JmlHariTunggakan > 30 GROUP BY a.ID ";(SELECT format(sum(z.REPAYMENT_AMOUNT),2) from bss_stmt_entry as z WHERE z.OUR_REFERENCE = a.ID) as repayment,
        $query = "select a.NomorNasabah,a.NomorRekening,a.NamaDebitur,a.ID,a.JmlHariTunggakan as DPD, a.FacilityType,a.PlafondAmount,(SELECT b.DESCRIPTION FROM bss_ld_sub_product as b WHERE b.ID = a.FacilityType) as ket_facility, a.STARTDATEPLAFOND,a.DATEEXPIRED,DAY(a.STARTDATEPLAFOND) as cycle, TIMESTAMPDIFF(MONTH,a.STARTDATEPLAFOND,a.DATEEXPIRED) as tenor,a.KodeCabang,(select q.nama_cabang from t_m_account as q  where q.LD_Temenos = a.ID) as Cabang,a.JmlHariTunggakan as DPD_EOM,a.COL as bucked,format((SELECT d.ANNUITY_REPAY_AMT FROM bss_ld as d WHERE d.ID = a.ID) , 2) as angsuran ,format(a.BakiDebet,2) as BakiDebet,format((SELECT f.DuePokok FROM t_m_account as f WHERE f.LD_Temenos = a.ID),2) as tunggakan_pokok ,format(a.DueBunga,2) as bunga,format((SELECT g.denda from t_m_account as g WHERE g.LD_Temenos = a.ID),2) as denda,format((SELECT sum(h.denda + h.DueBunga + h.DuePokok) FROM t_m_account as h WHERE h.LD_Temenos = a.ID),2) as total_tagihan ,(SELECT i.OPEN_ACTUAL_BAL FROM bss_account as i WHERE i.ID = a.RepayPrincSettleAcc) as saldo_tabungan, (SELECT j.L_TGL_RES from bss_limit as j WHERE j.ID=a.LimitID) as tgl_restru ,(SELECT k.L_NO_RES from bss_limit as k WHERE k.ID=a.LimitID) as restru_ke, (SELECT l.ADDRESS from bss_customer as l WHERE l.ID = a.NomorNasabah) as alamat,(SELECT m.POST_CODE from bss_customer as m WHERE m.ID = a.NomorNasabah) as postcode,(SELECT n.SMS_1 from bss_customer as n WHERE n.ID = a.NomorNasabah) as notlp,(SELECT o.EMAIL_1 from bss_customer as o WHERE o.ID = a.NomorNasabah) as email, (SELECT REPLACE(format(sum(z.REPAYMENT_AMOUNT),2),'-','') from bss_stmt_entry as z WHERE z.OUR_REFERENCE = a.ID) as repayment,(SELECT x.f_id from bss_stmt_entry as x WHERE x.OUR_REFERENCE = a.ID  ORDER BY x.f_id DESC limit 1) as tanggal from bss_cad as a";
        $data = $this->db2->query($query)->result();
        return $data;
    }
}
